apiVersion: v1
kind: ConfigMap
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: shipping # service name
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports: 
  - name: http
    protocol:  TCP
    port: 8080 # service port
    targetPort: 8080 # container port
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app

spec:
  replicas: 1
  selector:
    matchLabels: 
      component: shipping
      project: roboshop
      tier: app

  template:
    metadata:
      labels: 
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: nareshkumart/shipping:v1
        resources:
          requesest:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: shipping
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa # hpa means HorizontalPodAutoscaler
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10

