apiVersion: v1
kind: ConfigMap
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---
apiVersion: v1
kind: service
metadata:
  name: user
  namespace: roboshop
  labels: 
    compenent: user
    project: roboshop
    tier: app
spec:
  selector:
    compenent: user
    project: roboshop
    tier: app  
  port:  
  - protocal: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: user
    namespace: roboshop
    labels: 
      compenent: user
      project: roboshop
      tier: app
spec:
  replicas: 1
  selector:
    matchLabels: 
      compenent: user
      project: roboshop
      tier: app
  template:
    metadata:
    labels: 
      compenent: user
      project: roboshop
      tier: app
    spec:
      containers:
        - name: user
          images: nareshkumart/user:v1
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:          
              cpu: "100m"
              memory: "256Mi"
          envFrom:
          - configMapRef:
              name: user

--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa # hpa means HorizontalPodAutoscaler
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
      


